/* THE VENDORED FILAMENT PROFILES — drift gate + the contract they arrive under.
 *
 * `viewer/js/filament-profiles.js` is the Filament Material Lab's authored per-filament finish,
 * reduced to the two scalars that actually travel and emitted here by their generator. It is what
 * makes a filament with a profile render at its own roughness instead of the ordinary 0.55.
 *
 * ⚠ OWNERSHIP IS INVERTED FROM part-material.js, WHICH IMPORTS IT — the same shape as
 * `layer-detail.js` and `requirement-scope.js`, and the opposite of `plate-poses.json`. We own the
 * finish spec and the key vocabulary, because a filament lands in FILAMENT_DB here before it has a
 * label to be keyed by at all. They own the per-label values. So the two halves of the gate swap
 * sides on this one import, on the rule `plate-poses-vendor.test.mjs` states: **each repo gates the
 * drift it can actually cause.**
 *
 *   HERE      someone hand-edits the copy      <- the pinned hash below
 *   THE LAB   someone edits a profile and      <- their generator's --check, and their unit gate,
 *             does not re-emit                    both of which re-derive the SOURCE SHA256 in the
 *                                                 banner from profiles/*.json
 *
 * ⚠ SO THE PIN IS NOT THE WHOLE GATE AND IS NOT MEANT TO BE. It cannot tell a current copy from a
 * stale one — both are "unchanged since I last looked". What it catches is the one failure this
 * repo can produce on its own: an edit made here to a file whose author is elsewhere. The staleness
 * half is unrunnable here, because the profiles it is derived from do not exist in this repo.
 *
 * ⚠ DERIVED FILE. Do not "fix" a failure here by editing the copy or this constant. Edit the
 * profile JSON in the Lab and run `node tools/build-filament-profiles.mjs`, which rewrites both
 * copies and re-stamps the banner. Then bump the pin, in the same commit.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FILAMENT_PROFILES, FILAMENT_PROFILE_COUNT } from '../viewer/js/filament-profiles.js';
import { partMaterialSpec } from '../viewer/js/part-material.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const VENDORED = join(root, 'viewer', 'js', 'filament-profiles.js');

/* ⚠ Bump ONLY after the Lab's profiles legitimately changed AND they have been re-emitted here. */
const PINNED_SHA256 = '717775dc31ffd1e7449b16c6ada175d44baac11179bde7a3d6730d4454e2f1a6';

/* ⚠⚠ HASH THE CANONICAL CONTENT, NEVER THE WORKING-COPY BYTES. Both repos STORE LF and a Windows
   working copy holds CRLF, so hashing raw bytes asks which OS checked the file out rather than what
   the file says — and it answers NO in every fresh clone and in CI while passing locally. That has
   already blocked one deploy on a copy that was correct. */
const canonical = (p) => Buffer.from(readFileSync(p, 'utf8').replace(/\r\n/g, '\n'), 'utf8');

test('the vendored profile table is the copy that was reviewed', () => {
  assert.ok(existsSync(VENDORED), 'viewer/js/filament-profiles.js is missing');
  assert.equal(createHash('sha256').update(canonical(VENDORED)).digest('hex'), PINNED_SHA256,
    'viewer/js/filament-profiles.js was edited here. It is DERIVED and the Lab owns it — '
    + 'edit the profile there, re-run their generator, then bump this pin.');
});

test('it still says where it came from, and from what', () => {
  /* The banner is the staleness half's only anchor. Their gate re-derives the source hash from
     profiles/*.json and compares it to this line; a copy without it cannot be checked at all. */
  const src = readFileSync(VENDORED, 'utf8');
  assert.match(src, /SOURCE OF TRUTH: filament-material-lab\/profiles\/\*\.json/);
  assert.match(src, /SOURCE SHA256:\s+[0-9a-f]{64}/);
  assert.match(src, /GENERATED BY:\s+filament-material-lab\/tools\/build-filament-profiles\.mjs/);
});

test('⚔ it imports nothing, which is what lets part-material.js stay loadable in plain node', () => {
  /* part-material.js is testable on both sides precisely because it pulls in no renderer. A
     dependency added here would travel through that import and take the property with it. */
  const src = readFileSync(VENDORED, 'utf8');
  const SPEC = /(?:\bfrom\s*|\bimport\s*\(?\s*|\bexport\s+\*\s+from\s*)(['"])([^'"]*)\1/g;
  assert.deepEqual([...src.matchAll(SPEC)].map((m) => m[2]), []);
});

test('⚔ a profile fires under a LABEL and under nothing else', () => {
  /* ⚠ THE DECISION OF 2026-09-07, GATED. A profile keys by filament label, and a label exists only
     where the user has assigned a custom palette. In instruction-colours mode — the default — and
     in the ?part= embed there is no label, so no profile resolves and the part renders the base
     finish plus layer detail. `activeLabel` in main.js is what produces the null; this pins that a
     null actually means the base. */
  const [label] = Object.keys(FILAMENT_PROFILES);
  const base = partMaterialSpec('Case');
  assert.equal(base.roughness, 0.55);
  assert.equal(base.profile, undefined);
  assert.deepEqual(partMaterialSpec('Case', { label: null }), base);
  assert.deepEqual(partMaterialSpec('Case', { label: 'a filament nobody has profiled' }), base);

  const profiled = partMaterialSpec('Case', { label });
  assert.equal(profiled.profile, label);
  assert.equal(profiled.roughness, FILAMENT_PROFILES[label].roughness);
  assert.equal(profiled.metalness, FILAMENT_PROFILES[label].metalness);
});

test('⚔ and it moves ONLY roughness and metalness', () => {
  /* Two scalars is the whole payload. A profile that could reach the class, the clearcoat or the
     envMapIntensity would be a second author of the surface spec, which is the thing this transport
     was chosen to avoid. */
  const [label] = Object.keys(FILAMENT_PROFILES);
  const base = partMaterialSpec('Case');
  const profiled = partMaterialSpec('Case', { label });
  const moved = Object.keys({ ...base, ...profiled })
    .filter((k) => JSON.stringify(base[k]) !== JSON.stringify(profiled[k]));
  assert.deepEqual(moved.sort(), ['metalness', 'profile', 'roughness']);
});

test('⚔ the base is untouched by landing a profile — 0.55 / 0.05 still ships', () => {
  /* ⚠ THE SHIP DECISION, AND IT IS THE ONE MOST EASILY LOST. Landing profile one does NOT move the
     ordinary part: every unprofiled filament, and every part in the default view, renders exactly
     what it rendered before. Moving 0.55 here would be a product-wide appearance change smuggled in
     under "landing profile one". */
  for (const key of ['Case', 'Drawer', 'ShelfInsert', 'Handle', 'Case:BODY']) {
    assert.equal(partMaterialSpec(key).roughness, 0.55, key);
    assert.equal(partMaterialSpec(key).metalness, 0.05, key);
  }
});

test('⚔ a purchased part and the plate transfer are both out of a profile\'s reach', () => {
  const [label] = Object.keys(FILAMENT_PROFILES);
  /* The foot is bought, not printed. `colorLocked` keeps activeLabel from ever handing it one, and
     the spec refuses it anyway — belt and braces, because only one of the two lives in this repo. */
  assert.deepEqual(partMaterialSpec('FootAdhesive', { label }),
    { kind: 'standard', roughness: 0.72, metalness: 0 });
  /* The plate finish describes what the BUILD PLATE did to a surface. A filament profile describes
     the filament, and cannot also describe that. */
  const holo = partMaterialSpec('Faceplate', { holographicPlate: true, plateContact: true, label });
  assert.equal(holo.roughness, 0.14);
  assert.equal(holo.profile, undefined);
});

test('the count is stated and agrees with the table', () => {
  assert.equal(FILAMENT_PROFILE_COUNT, Object.keys(FILAMENT_PROFILES).length);
});
