r"""Rebuild the Shelf Inserts source blend from the shipped STLs.

    blender --background --python build_shelf_insert_blend.py -- <out.blend>

WHY THIS IS COMMITTED - and what it does NOT promise. `Blender Files/` and
`GLB Library/` are both gitignored, so the source blend that `gen2_jobs.json`'s
seven shelf jobs point at exists only on Joey's disk. This preserves the import
and normalisation RECIPE for it: given the original shelf STL set and a
compatible Blender, it reconstructs that blend.

⚠ IT IS NOT A VERIFIED DERIVATION, and must not be read as one. The STL inputs
are NOT committed and their hashes are NOT recorded, nothing pins the Blender or
exporter version, and NOTHING checks that a reconstruction matches the GLBs that
actually shipped. Contrast `derive_adhesive_foot.py`, which consumes committed
inputs, has a `--check` that diffs regenerated bytes against every shipped copy,
and a test that refuses to bless a stale pair. This script is the same CLASS of
asset but carries none of that assurance: it is provenance KNOWLEDGE, not
provenance PROOF. If that ever needs to change, the two missing pieces are
committed source-STL hashes and a compare-to-`viewer/parts` mode - both of which
need Blender, so neither can run in CI.

WHAT IT DOES, per part: import the STL, flip it 180 degrees about X so it sits
in INSTALLED orientation (plate face UP, clips hanging DOWN - the STLs are
authored face-down for printing), recentre X/Y on the bbox and drop the bottom
to Z=0 (the house canonical origin), clear materials, and file it into a
per-length collection. `report` prints a before/after read of which face carries
the large flat plate, so a silent orientation regression is visible in the log.

WARNINGS, both learned the hard way on this batch:

  1. `hide_viewport = True` SILENTLY BREAKS TRANSFORM BAKING. A hidden object is
     dropped from the depsgraph, so its `matrix_world` stays identity forever -
     the first export baked nothing and produced 28 upside-down parts. Bake an
     explicit rotation matrix (as below, `me.transform(FLIP)`) and never trust
     `matrix_world` on a hidden object. Cycles renders are unaffected: the
     render depsgraph is separate, which is exactly why the thumbnails looked
     right while the GLBs were wrong.

  2. The mesh is transformed, NOT the object. Object-level rotation would leave
     the exporter to bake it, and the export worker's `depth_mode: center` then
     has to agree about which axis is depth. Transforming the mesh means the
     MESH DATA already carries the installed orientation and the canonical local
     origin. ⚠ It does NOT mean the blend holds exactly what ships: each object
     is then parked on a layout grid (`ob.location`), and `gen2_batch.py` does
     its own canonical rebasing at export.

The orientation assertion below is the point of the whole file. `gen2_batch.py`
reporting "canonical OK" CANNOT catch an upside-down part - canonical rebasing
recentres an inverted mesh just as happily as a correct one, which is exactly
why the first batch shipped 28 wrong parts while every check passed. So this
refuses to write rather than reporting and continuing.
"""

import bpy, os, math, sys
from mathutils import Matrix

# argv after `--`: <out.blend> [stl-root].  The STL root may also come from
# GEN2_SHELF_STL_ROOT. There is deliberately NO built-in default: the source
# lives outside the repo, on one machine, and a hardcoded path would make this
# look runnable by a cloner when it is not.
_args = sys.argv[sys.argv.index("--")+1:]
if not _args:
    sys.exit("usage: blender -b --python build_shelf_insert_blend.py -- <out.blend> [stl-root]\n"
             "       (stl-root may instead be set in GEN2_SHELF_STL_ROOT)")
dst = _args[0]
SHARE = (_args[1] if len(_args) > 1 else os.environ.get("GEN2_SHELF_STL_ROOT", "")).rstrip("\\/")
if not SHARE or not os.path.isdir(SHARE):
    sys.exit("shelf STL root not found: %r\n"
             "  pass it after the output path, or set GEN2_SHELF_STL_ROOT.\n"
             "  On Joey's machine it is: D:\\Claude - Model Sharing\\GEN2" % SHARE)
bpy.ops.wm.read_factory_settings(use_empty=True)
sc = bpy.context.scene
sc.unit_settings.system = 'METRIC'
sc.unit_settings.scale_length = 0.001

FLIP = Matrix.Rotation(math.pi, 4, 'X')   # print orientation -> INSTALLED (plate up, clips down)
report = []

def add(stl, name, col, gx, gy):
    if not os.path.isfile(stl):
        sys.exit("missing source STL: %s" % stl)
    before = set(bpy.data.objects)
    bpy.ops.wm.stl_import(filepath=stl)
    ob = [o for o in bpy.data.objects if o not in before][0]
    me = ob.data
    zs0 = [v.co.z for v in me.vertices]
    def flat(m, lvl, tol=0.05):
        a = 0.0
        for p in m.polygons:
            vs = [m.vertices[i].co for i in p.vertices]
            if all(abs(v.z-lvl) < tol for v in vs):
                s = 0.0
                for i in range(len(vs)):
                    s += vs[i].x*vs[(i+1)%len(vs)].y - vs[(i+1)%len(vs)].x*vs[i].y
                a += abs(s)/2
        return a
    plate_before = 'bottom' if flat(me, min(zs0)) > flat(me, max(zs0)) else 'top'
    me.transform(FLIP)
    xs=[v.co.x for v in me.vertices]; ys=[v.co.y for v in me.vertices]; zs=[v.co.z for v in me.vertices]
    me.transform(Matrix.Translation((-(min(xs)+max(xs))/2, -(min(ys)+max(ys))/2, -min(zs))))
    me.update()
    zs2 = [v.co.z for v in me.vertices]
    plate_after = 'bottom' if flat(me, min(zs2)) > flat(me, max(zs2)) else 'top'
    ob.name = name; me.name = name
    ob.matrix_world = Matrix.Identity(4)
    ob.location = (gx, gy, 0)
    ob.hide_viewport = False; ob.hide_render = False; ob.hide_select = False
    me.materials.clear()
    for c in ob.users_collection: c.objects.unlink(ob)
    col.objects.link(ob)
    # ⚠ FAIL CLOSED. These parts are authored FACE-DOWN for printing, so the
    # large flat plate must start at the bottom and end at the top. Anything
    # else means the STLs were re-exported already-flipped (or the flip was
    # dropped), and the batch would produce confidently-wrong geometry that
    # every downstream canonical check still passes.
    if (plate_before, plate_after) != ('bottom', 'top'):
        sys.exit("ORIENTATION: %s reads plate %s -> %s, expected bottom -> top.\\n"
                 "  The STL is probably already in installed orientation. Do NOT\\n"
                 "  'fix' this by removing the flip without re-checking every part."
                 % (name, plate_before, plate_after))
    report.append((name, plate_before, plate_after, [round(v,1) for v in ob.dimensions]))

for i, L in enumerate((59,115,165,185,240,270)):
    col = bpy.data.collections.new(f'ShelfInserts_{L}')
    sc.collection.children.link(col)
    for w in (1,2,3,4):
        add(os.path.join(SHARE, str(L), 'Shelf Inserts', f'{L}-{w}W Shelf Insert.stl'),
            f'{L}-{w}W Shelf Insert', col, w*400.0, i*320.0)
lc = bpy.data.collections.new('ShelfLips')
sc.collection.children.link(lc)
for w in (1,2,3,4):
    add(os.path.join(SHARE, 'Shelf Insert Lips', f'Shelf Lip - {w}W.stl'),
        f'Shelf Lip - {w}W', lc, w*400.0, -260.0)

# 24 inserts (6 lengths x 4 widths) + 4 lips. A short count means a source file
# was missing or a collection did not receive its objects - either way the seven
# tracked jobs in gen2_jobs.json would export an incomplete set.
EXPECTED = 6 * 4 + 4
if len(report) != EXPECTED:
    sys.exit("expected %d parts, built %d" % (EXPECTED, len(report)))
if len(sc.objects) != EXPECTED:
    sys.exit("expected %d objects in the scene, found %d" % (EXPECTED, len(sc.objects)))

bpy.ops.wm.save_as_mainfile(filepath=dst, compress=True)
print("[build] objects:", len(sc.objects), "(all %d expected)" % EXPECTED)
for r in report: print("[build]", r)
